### ISSUE TITLE
Is there any relationship between Data Packages and DCAT?

### ISSUE THREAD

**Issue by tedstrauss** [frictionlessdata/ckanext-datapackager#53]
They seem to be distinct (competing) standards for describing the same thing. Is that right?

**Comment by GeraldGrootRoessink** [comment]
May this helps?
https://gitlab.com/european-data-portal/ckanext-edp/wikis/schema

**Comment by tedstrauss** [comment]
thanks
That page says "DCAT-AP" mapping. Can you remind me what does AP stand for?

**Comment by GeraldGrootRoessink** [comment]
It stands for application profile.  In this case for European Data Portals.

**Comment by GeraldGrootRoessink** [comment]
The datapackage-definition (https://frictionlessdata.io/specs/data-package/) states: 

> "Adherence to the specification does not imply that additional, non-specified properties cannot be used: a descriptor MAY include any number of properties in additional to those described as required and optional properties." 

In the enclosed example I have added typical DCAT-fields used in the CKAN-DCAT-extension. So CKAN wil spit it out in DCAT-form.

[datapackage.zip](https://github.com/frictionlessdata/ckanext-datapackager/files/1708619/datapackage.zip)

**Comment by amercader** [comment]
DCAT is a generic vocabulary to be used when describing datasets using RDF (that can be further described in an Application Profile as @GeraldGrootRoessink mentioned). Data Packages are a light-weight specification for both the concepts and the format (`datapackage.json` file), with an emphasis on interoperability and transport between platforms.
Both serve different purposes so it will largely depend on your needs. 

They can also be used in conjunction. You can probably quite easily adapt a JSON-LD DCAT compliant representation to be a valid data package.
Also you can use both, enabling both ckanext-dcat and ckanext-datapackager in your extension will allow you output and ingest both.

Hope this helps, feel free to reopen the issue if you want to discuss further.
