### ISSUE TITLE
 Datapackage: There are 1 validation errors (see exception.errors)

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [frictionlessdata/ckanext-datapackager#64]
Hi,
Datapackages seem a nice way to improve the quality of data (in our  case about education in the Netherlands) with appropriate metadata. We have an instance of CKAN running including extensions datastore and datapackager. 
Tried importing a minimal datapackage and ran into a validation error (message text in title). I would like to find out what's wrong.  Where should I Iook?
Appreciate your reply.
Thanks Gerald

[minimalcsv.zip](https://github.com/frictionlessdata/ckanext-datapackager/files/1603930/minimalcsv.zip)

**Comment by Stephen-Gates** [comment]
Hi @GeraldGrootRoessink 

I'm not sure about the second resource in your data package. 

If I was creating a data package for datetime.csv it would look like this (but without the "datatimes" typo)

```
{
  "name": "datetimes",
  "resources": [
    {
      "name": "datatimes",
      "path": "data/datetimes.csv",
      "schema": {
        "fields": [
          {
            "name": "num",
            "type": "integer"
          },
          {
            "name": "datetime",
            "type": "string"
          }
        ]
      }
    }
  ]
}
```

Note that a current bug #61 prevents the `schema` property from being uploaded.

![image](https://user-images.githubusercontent.com/9379524/34593148-c68d5f02-f214-11e7-8434-d7ebe7044c51.png)

**Comment by GeraldGrootRoessink** [comment]
Thanks,
Followed your example more closely and after downloading https://github.com/frictionlessdata/ckan-datapackage-tools I could upoad the data. Alas, without the schema-part, as you said. That would really help.
