### ISSUE TITLE
Schema in CKAN not exported (internal server error)

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [frictionlessdata/ckanext-datapackager#65]
This is the opposite of #61. After importing a tabelschema in CKAN it can not be downloaded as part of een datapackage.json (internal server error). By the way, it will correctly be exported by the package_show api.  No such luck with the datastore_search api. That one shows the field-structure created by the datapusher.

**Comment by amercader** [comment]
The `schema` field was not part of the original implementation so any work on that front would be welcomed. There shouldn't be an exception though. Can you paste the stacktrace?

**Comment by amercader** [comment]
Did the latest changes fix the internal error @GeraldGrootRoessink ?

**Comment by GeraldGrootRoessink** [comment]
Yes! Thank you very much.
This is in my  (nonsensical) output:

    "schema": {
        "fields": [
          {
            "rdfType": "http://lod.duo.nl/cdm/def/v0/regelnummer", 
            "title": "kolom 1", 
            "type": "string", 
            "name": "regel", 
            "format": "default"
          }, 
          {
            "rdfType": "http://lod.duo.nl/cdm/def/v0/BRIN", 
            "title": "kolom 2", 
            "type": "integer", 
            "name": "brin", 
            "format": "default"
          }, 
          {
            "rdfType": "http://lod.duo.nl/cdm/def/v0/postcode", 
            "title": "kolom 3", 
            "type": "number", 
            "name": "pc", 
            "format": "default"
          }
        ], 
        "missingValues": [
          ""
        ]
      }
Going for a real example now.
