### ISSUE TITLE
Missing ckan_datapackage_tools dependency

### ISSUE THREAD

**Issue by liordaganleib-d** [frictionlessdata/ckanext-datapackager#71]
When installing version 1.0.3 without installing dependencies, I get the error "ImportError: No module named ckan_datapackage_tools". Installing dependencies seems to solve it but it should be imported automatically.

**Comment by roll** [comment]
@liordaganleib-d 
ckan recommends to install extensions like this:
```
    pip install -e git+https://github.com/frictionlessdata/ckanext-datapackager.git@master#egg=ckanext-datapackager && \
    pip install -r https://raw.githubusercontent.com/frictionlessdata/ckanext-datapackager/master/requirements.txt
```
So `ckan_datapackage_tools` is listed in `requirements.txt` no in `setup.py`
