### ISSUE TITLE
Couldn't find a readme UnityEngine.Debug:Log(Object) ReadmeEditor:SelectReadme() (at Assets/TutorialInfo/Scripts/Editor/ReadmeEditor.cs:59) ReadmeEditor:SelectReadmeAutomatically() (at Assets/TutorialInfo/Scripts/Editor/ReadmeEditor.cs:26) UnityEditor.EditorApplication:Internal_CallDelayFunctions()

### ISSUE THREAD

**Issue by prashmanvi1235** [frictionlessdata/ckanext-datapackager#74]
# Overview

Please replace this line with full information about your idea or problem. If it's a bug share as much as possible to reproduce it

---

Please preserve this line to notify @amercader (lead of this repository)

**Comment by amercader** [comment]
I'm pretty sure this is the wrong repo for this
