### ISSUE TITLE
Status of this plugin

### ISSUE THREAD

**Issue by mcarans** [frictionlessdata/ckanext-datapackager#76]
# Overview

Just wondering what is the status of this plugin? Is it still being developed? Is it still needed or is its functionality built into newer CKAN versions?

---

Please preserve this line to notify @amercader (lead of this repository)

**Comment by amercader** [comment]
@mcarans sorry for the late reply, but we are planning on updating this plugin to support modern CKAN versions and Python 3. The work will likely be done over the summer, see https://github.com/frictionlessdata/ckanext-datapackager/issues/77
