### ISSUE TITLE
Support for CKAN 2.9 / Python 3

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/ckanext-datapackager#77]
The plugin hasn't been updated in a while and we need to ensure it works with modern CKAN versions

Steps

- [x] Remove Travis CI, run tests on Github Actions against CKAN 2.7 and CKAN 2.8. A simple extension setup like [ckanext-geoview](https://github.com/ckan/ckanext-geoview/blob/master/.github/workflows/test.yml) should be a good starting point. 
- [x] Once the tests pass, enable the CKAN 2.9 ones, which will surely break.
- [x] The full py3 / CKAN 2.9 upgrade guide can be found [here](https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions). Having had a quick look it seems that the only upgrade work needed will be:
    - Controllers / Blueprint mixins
    - Python 3 support. Use `six` to keep compatibility with Python 2 for now
- [x] Once the current functionality works on CKAN 2.9 (tests passing) we can consider modernizing the FD requirements, notably the `ckan-datapackage-tools` which is now called [frictionless-ckan-mapper](https://github.com/frictionlessdata/frictionless-ckan-mapper). This is responsible for mapping CKAN datasets <-> DataPackages . We need to see if there are breaking changes between the two implementations.

**Comment by aivuk** [comment]
@amercader I finished setting up the github actions for running the tests as you can see in this [PR](https://github.com/frictionlessdata/ckanext-datapackager/pull/78). I started with the migration to Python 3 and I'm already trying to run the tests on CKAN 2.9. I have one question: is the idea to have this module working only for CKAN >= 2.9? If not, is not a better idea to have a separate repository for the CKAN 2.9 extension?

**Comment by amercader** [comment]
@aivuk, no, the same code base should work on py2/py3 (ckan 2.7 to 2.9), unless there's a major thing preventing it which I don't expect on this extension. The same was done on much more complex extensions

**Comment by amercader** [comment]
ckanext-datapackager 1.1.0 supports CKAN 2.9 and py3
